---
- name: Check Required Variables
  fail: msg="{{ item }} is not defined"
  when: item is not defined
  loop:
    - nfs_mount.mount_options
    - nfs_mount.mount_point
    - nfs_mount.nfs_server
    - nfs_mount.nfs_server_export